## **Rule 2:** Read abstracts and reviews {-#rule2}

:::{.indent}
Here's another piece of advice if you are close to the end of your PhD (let's say around half to one year before submission) and you have a lot of papers in your to-read list: **focus on abstracts and review papers**.
The assumption here is that you don't need all the details from a paper, just the main take-home messages.
Abstracts were created exactly for that reason.
Some papers nowadays also include a Highlights section, facilitating a quick overview of the key results.
Don't spend your time reading the Methods section of a paper, though a quick look at the figures and the Discussion section can only be beneficial.
Don't waste your time on technical papers at this point, you will rarely need them if at all.
Reviews will point you to other important papers that you may have missed.
A good review paper is one where you have the possibility of reading about the work from other papers, in a way that is embedded in a larger story, similar to what you will be doing in your thesis writing.
So you might want to spend a considerate amount of time reading reviews rather than any other type of scientific paper at this point of your PhD period.
:::

:::{.indent}
By reading abstracts and reviews, you most probably will obtain pieces of information that may seem unconnected to what you already know.
What is important to remember is that *you have to make the connections* and make that knowledge your own.
**Reading by itself is not enough**.
So, what is the best way to assimilate knowledge?
To answer that, let's assume that you have an internal knowledge representation structure, which I like to think of as a tree (let's call it your own *tree of knowledge*).
That tree is going to be the main source for your PhD story (see [Rule 1](#rule1)) and that is why it is extremely important to take good care of it.
*You have to help that tree grow*.
The knowledge you've acquired from reading scientific papers needs to be a part of that tree.
One technique to accomplish exactly that, i.e. integrate new information into your internal tree of knowledge, is **force remembering**.
This means that you have to force yourself to think about what you have been reading at times when you are doing something else (walking, cooking, e.g. take your pick).
The simplest way to start remembering is by repeating in your mind words and sentences that you've read (or your own variations of them) and enter a process of internal dialogue with yourself.
You start asking questions and you try to find answers to them.
During this cognitive exercise, you subject the information you have started remembering to analysis, visualization and interpretation.
The goal of this process is to gain a deeper understanding of what you've read, and incorporate that into your own knowledge tree.
It might be of help to think of this whole mental activity in a visual manner: refining pieces of information and attaching them at appropriate branches in your knowledge tree!
:::

:::{.indent}
Using the aforementioned remembering technique along with your reading practice, will help you **build your own personalized tree of knowledge**, fine-tuned to the subject you will be writing about in your PhD thesis.
Moreover, the tree's size as well as depth will be considerably increased.
Note that any other mnemonic or knowledge assimilation technique might work as well.
The key point is to be active in your reading and efficiently absorb knowledge.
As Confucius once said, "*Learning without thought is labor lost; thought without learning is perilous*".
So nourish your tree with knowledge, give it the water and sunlight that it deserves!
:::

:::{.quote}
Read mainly abstracts and reviews during the last months of your PhD.
:::
