## **Rule 5:** Select several diverse workplaces {-#rule5}

:::{.indent}
Continuing from the previous rules, now you know what to do to have the proper background knowledge (read papers) and how to be more reading-efficient (focus on abstracts and reviews mostly).
You also know that you need to lay out your upcoming writing work in a document (the skeleton of the story) and make a plan with regard to when you are going to start and finish the writing.
Another factor that will influence your writing is the environment where you will be working from.
This is one of the most important rules of this collection.
My advice here is two-fold: first, **make sure you have your working environment ready for the task ahead** and second, **have at your disposal several options for places that you could go and do some writing**.
:::

:::{.indent}
But first things first.
When the prospect of writing a PhD thesis is on the horizon, we usually resort to a familiar place to complete such a task: our home.
The reasons are multiple.
Quiet, which makes it easy to focus.
No disturbances, no interactions either ^[Homes are not always the quiet places I portray them to be. Having a family or living in a shared apartment for example can be valid reasons to use your university office or some other place as first option for your writing sessions. In either case, it seems to me that the more daunting the writing task, the more people tend to seek out quiet environments to increase their work efficiency, no matter where these are located.].
Easy to regulate and make it fit to your needs and standards.
Not to mention, access to kitchen and toilet without too much of a trouble.
Despite these conveniences, there might still be things that require your careful attention to transform your home environment to a workplace suitable for the ensuing writing work.
For example, do you have a proper screen (if that's what is best for you), comfortable chair and desk?
Access to some nice view (nature if possible)?
I can not advise you on what is the perfect writing home environment since this is entirely a matter of personal taste.
I can insist though that you **spend the time required to make your workplace as ideal for you as possible**.
So make sure that the basic preconditions are there to efficiently work from home.
If you have already lived one or more quarantines due to COVID-19, then you know exactly what I am talking about!
:::

:::{.indent}
So your home might be one place where you will be doing some writing.
Another option?
Your work office seems like a possible candidate.
Since you want to write a PhD thesis, I assume that you are a PhD candidate and therefore you should have an office space at a university.
Apply the same reasoning as described above and think: "*How can I improve my office space and make it a welcome environment for my thesis writing*"?
You could add some family pictures for example.
Is the surface of your desk clean, with no coffee cups or papers scattered around?
If not, then how do you expect to write something of order in such a chaotic environment?
Maybe you can start by cleaning your desk, a certain level of tidiness can surely be of some help.
Or maybe you can forget all about working from the office, since it is a cubicle workspace with lots of other students and it can get too much noisy for your taste.
Then how about the university's library?
Or some other cozy place in the university that you may know of?
An on-campus café perhaps?
A nice suggestion is to **book a study room for some hours once every week**, motivating you to go in that place and do some writing.
Overall, a university campus can be the host of several writing spots which you should know about beforehand, so make sure you do your spatial research!
:::

:::{.indent}
Having a provision of different places (and backup places) suitable for writing sessions, is a central element to this rule.
The keyword here is **diversity**.
It is one of the principles that you can apply to *break the monotony of writing*.
So you have all your standard workplaces (home and office) figured out.
Sometimes we need the absolute quiet of our home, sometimes we get inspired by having a conversation in our office and seeing some of our colleagues.
Great.
Now extend this concept a bit further.
How about working from a café for a change?
Cafés can be fairly quiet places during regular working days and hours.
I like to view them as libraries with a bit more noise than usual and constant music in the background, a combination that acts as an alternative working environment.
Coordinating also with a friend and having some company might actually be a good idea.
Being voluntarily exposed to social environments might trigger thoughts in your brain that sitting alone in your home or office just won't do.
Your regulated working environments may lack the certain level of *randomness* that could be the key ingredient of a productive writing session.
Just walking to the café might be beneficial to your unconscious mind, providing you with the essential stimulus and inspiration.
Maybe you meet someone you haven't seen for a while.
Maybe your favorite song from your high school years suddenly plays inside the café, inspiring you to find the missing word you were searching for.
And you get the chance to drink some quality coffee (hopefully).
The aforementioned experiences are all directly related to **the notion of reward**.
You can think of reward as a way to boost your psyche at times when writing scientific prose just doesn't seem to be the best thing in the world.
Or as I like to say, "*more espresso, less depresso*".
:::

:::{.indent}
*Reward is a very powerful motive*.
You can use it to persuade yourself to do things you don't feel like doing.
Days will come when your motivation levels will be extremely low and you won't feel like writing at all.
**Don't spend time thinking about it.
Act.**
Any type of reward would be welcome at moments such as these.
Go out to the nearest café and get a cup of coffee.
I believe that is the simplest reward you can give to yourself and which will encourage you to do some writing work.
It is at least *something*.
Having some coffee is a million times better than staying inside and trying to fight against your inner rebelling self that wants to procrastinate and do anything other than write.
**So pay for the damn coffee and get that cookie as well**!
Note that caffeine is one of the most used psychoactive substances in the world.
Be also aware of the fact that the beneficial effects of caffeine (*concentration* and *mental focus* are the most important for us here) decrease over time with regular consumption, resulting in the manifestation of caffeine tolerance.
In other words, you need ever-increasing amounts of caffeine to reap its benefits.
Therefore, I advise you to properly regulate your caffeine intake in your everyday life, with some days having a bit more and other days a bit less.
Cutting down your caffeine consumption for a couple of days can be very rewarding.
After some time, drinking a regular cup of coffee will result in a very pleasant experience and will significantly enhance your mental performance.
:::

:::{.indent}
I used the example of working from cafés to demonstrate the importance of a reward system and of how such a system can positively influence your writing progress.
Reward here was having some coffee and being exposed to a different environment.
But you don't have to restrict yourself to the rewards or workplaces that I mentioned.
They just happened to be the most accessible to me.
It could very well be the case that some other types of rewards or work environments are more fitting for you.
So take advantage of them when you deem appropriate to do so.
The argument of having several working environments (and the potential rewards they offer) is of crucial importance to the PhD thesis writing.
Only if you have several options available, you can make a choice of a working environment that is better for you at a specific time.
Remember that you have to **be in the right place, at the right time**.
If you have only one standard workplace though, then you don't allow yourself the benefit of a choice.
You constrain yourself.
It's better to have a few places to work from.
So have them figured out, before you start writing.
Thus you may alleviate some of the suffering that is associated with the writing ordeal that is the PhD thesis.
:::

:::{.quote}
Select several diverse workplaces, and if applicable, make the corresponding environments suitable for the upcoming writing task.
:::
